#!/bin/bash

# cd into each folder and trigger the makefile

echo "Making AStar"
cd AStar
./makefile

echo "Making FieldOfView"
cd ..
cd FieldOfView
./makefile

echo "Making Noise"
cd ..
cd Noise
./makefile